#!/bin/bash

if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    echo "Only linux is support at the moment"
fi

# check number of arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <scenario_name>"
    exit 1
fi

PLATFORM=$(uname)

mkdir -p $1/bin
if [ "$PLATFORM" = "Darwin" ]; then
    cross build --all --release --locked --target=x86_64-unknown-linux-gnu && for i in $(find ../../target/x86_64-unknown-linux-gnu/release/ -perm +111 -depth 1); do cp -v $i  $1/bin ; done
    cross build --all --release --locked --target=x86_64-unknown-linux-gnu --examples && for i in $(find ../../target/x86_64-unknown-linux-gnu/release/examples/ -perm +111 -depth 1); do cp -v $i  $1/bin ; done
else
    cargo build --all --release --locked && for i in $(find ../../target/release/ -executable -type f | grep -v -); do cp -v $i  $1/bin ; done
    cargo build --all --release --locked --examples && for i in $(find ../../target/release/examples/ -executable -type f | grep -v -); do cp -v $i  $1/bin ; done
fi

./clab $1 || exit 255

RESULT=$(cat $1/experiment.log | grep "EXPERIMENT RESULT: ")

if [[ $RESULT =~ "EXPERIMENT RESULT: Success" ]]; then
   echo "$RESULT"
   exit 0
elif [[ $RESULT =~ "EXPERIMENT RESULT: Failed" ]]; then
    echo "$RESULT"
    exit 1
fi